"use server";
import { and,eq } from "drizzle-orm";
import { z } from "zod";
import { redirect } from "next/navigation";
import { revalidatePath } from "next/cache";
import { requireRole } from "@/lib/auth/session";
import { getDatabase } from "@/lib/db/client";
import { appSettings,terms,termEnrollments } from "@/lib/db/schema";
import { canAccessTerm } from "@/lib/learning/queries";
import { getLocalizedUserName } from "@/lib/users/name";
import { saved,denied,failed,text,type ActionState } from "@/lib/workflows";
import type { Locale } from "@/lib/i18n/config";
// Skyroom's official API: https://data.skyroom.online/help/webservice.html
async function skyroom(action:string,params:Record<string,unknown>){const key=process.env.SKYROOM_API_KEY;if(!key)throw new Error("Skyroom unavailable");const response=await fetch(`https://www.skyroom.online/skyroom/api/${encodeURIComponent(key)}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,params}),cache:"no-store",signal:AbortSignal.timeout(15000)});if(!response.ok)throw new Error("Skyroom unavailable");const result=z.object({ok:z.boolean(),result:z.unknown().optional(),error_code:z.number().optional()}).parse(await response.json());if(!result.ok){if(result.error_code===15)return null;throw new Error("Skyroom rejected request");}return result.result;}
function safeRoomUrl(value:unknown){const url=z.url().parse(value);const parsed=new URL(url);if(parsed.protocol!=="https:"||!parsed.hostname.endsWith(".skyroom.online"))throw new Error("Unexpected classroom URL");return url;}
export async function prepareOnlineClass(termId:string,locale:Locale):Promise<ActionState>{const user=await requireRole(["admin","teacher"]);if(!z.uuid().safeParse(termId).success||!await canAccessTerm(user,termId,true))return denied(locale);if(!process.env.SKYROOM_API_KEY)return {error:text(locale,"سرویس اسکای‌روم هنوز فعال نشده است. از پیوند کلاس ثبت‌شده در ترم استفاده کنید.","Skyroom is not configured yet. Use the classroom link configured on the term.")};try{await getDatabase().transaction(async tx=>{const[term]=await tx.select().from(terms).where(eq(terms.id,termId)).for("update");if(!term||term.deliveryMode==="in_person"||["completed","cancelled"].includes(term.status))throw new Error("Class unavailable");const key=`skyroom.term.${termId}`;const [stored]=await tx.select().from(appSettings).where(eq(appSettings.key,key));if(stored)return;const name=`cactus-${termId}`;const existing=await skyroom("getRoom",{name});const roomId=existing?z.object({id:z.number().int().positive()}).parse(existing).id:z.number().int().positive().parse(await skyroom("createRoom",{name,title:term.titleFa.slice(0,128),guest_login:false,op_login_first:true,max_users:(term.capacity??20)+5,...(process.env.SKYROOM_SERVICE_ID?{service_id:Number(process.env.SKYROOM_SERVICE_ID)}:{})}));await tx.insert(appSettings).values({key,value:String(roomId)});});}catch{return failed(locale);}revalidatePath("/panel","layout");return saved(locale);}
export async function joinOnlineClass(termId:string,locale:Locale):Promise<ActionState>{const user=await requireRole(["admin","teacher","student"]);if(!z.uuid().safeParse(termId).success||!await canAccessTerm(user,termId))return denied(locale);const db=getDatabase();const[term]=await db.select().from(terms).where(eq(terms.id,termId));if(!term||term.deliveryMode==="in_person"||term.status!=="active")return denied(locale);if(user.role==="student"){const[enrollment]=await db.select().from(termEnrollments).where(and(eq(termEnrollments.termId,termId),eq(termEnrollments.studentId,user.id),eq(termEnrollments.status,"active")));if(!enrollment)return denied(locale);}
 const [room]=await db.select().from(appSettings).where(eq(appSettings.key,`skyroom.term.${termId}`));if(!room){if(term.meetingUrl&&/^https?:\/\//.test(term.meetingUrl))redirect(term.meetingUrl);return denied(locale);}let url:string;try{url=safeRoomUrl(await skyroom("createLoginUrl",{room_id:Number(room.value),user_id:user.id,nickname:getLocalizedUserName(user,locale),access:user.role==="student"?1:3,concurrent:1,language:locale,ttl:900}));}catch{return failed(locale);}redirect(url);}
