services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        http_proxy: http://10.113.0.1:8118
        https_proxy: http://10.113.0.1:8118
        HTTP_PROXY: http://10.113.0.1:8118
        HTTPS_PROXY: http://10.113.0.1:8118
    container_name: nextjs-app
    restart: always
    ports:
      - '127.0.0.1:3000:3000'
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    env_file:
      - .env.production

networks:
  app-network:
    driver: bridge