"use client";

import { useTransition } from "react";
import { deleteComment, moderateComment } from "@/app/(panel)/panel/admin/comments/actions";
import { useFeedback } from "@/components/feedback/feedback-provider";
import { PanelActionSpinner, PanelDeleteIcon, PanelTableActionButton, PanelTableActions } from "@/components/panel/ui";
import type { Locale } from "@/lib/i18n/config";
export function AdminCommentActions({ commentId, locale }: { commentId: string; locale: Locale }) { const [pending, startTransition] = useTransition(); const { confirm, toast } = useFeedback(); const isFa = locale === "fa"; function moderate(status: "approved" | "rejected") { startTransition(async () => { const result = await moderateComment(commentId, status, locale); if (result.error) toast.error(result.error); else if (result.success) toast.success(result.success); }); } async function remove() { const ok = await confirm({ title: isFa ? "حذف دیدگاه؟" : "Delete comment?", description: isFa ? "این دیدگاه برای همیشه حذف می‌شود." : "This comment will be permanently deleted.", confirmLabel: isFa ? "حذف" : "Delete" }); if (!ok) return; startTransition(async () => { const result = await deleteComment(commentId, locale); if (result.error) toast.error(result.error); else if (result.success) toast.success(result.success); }); }
  return <PanelTableActions><PanelTableActionButton label={isFa ? "تأیید دیدگاه" : "Approve comment"} disabled={pending} onClick={() => moderate("approved")}><svg viewBox="0 0 20 20" aria-hidden="true" className="size-4.5" fill="none" stroke="currentColor" strokeWidth="1.8"><path strokeLinecap="round" strokeLinejoin="round" d="m4 10 4 4 8-9" /></svg></PanelTableActionButton><PanelTableActionButton label={isFa ? "رد دیدگاه" : "Reject comment"} disabled={pending} onClick={() => moderate("rejected")}><svg viewBox="0 0 20 20" aria-hidden="true" className="size-4.5" fill="none" stroke="currentColor" strokeWidth="1.8"><path strokeLinecap="round" d="m5 5 10 10M15 5 5 15" /></svg></PanelTableActionButton><PanelTableActionButton label={isFa ? "حذف دیدگاه" : "Delete comment"} tone="danger" disabled={pending} onClick={remove}>{pending ? <PanelActionSpinner /> : <PanelDeleteIcon />}</PanelTableActionButton></PanelTableActions>; }
