import Link from "next/link";
import { CommentForm } from "@/components/comments/comment-form";
import { DeleteOwnCommentButton } from "@/components/comments/delete-own-comment-button";
import type { CurrentUser } from "@/lib/auth/session";
import type { CommentStatus } from "@/lib/db/schema";
import { getDictionary } from "@/lib/i18n/dictionaries";
import { localeConfig, type Locale } from "@/lib/i18n/config";

type CommentItem = { id: string; authorId: string | null; authorNameFa: string; authorNameEn: string; body: string; status: CommentStatus; createdAt: Date };
export function CommentsSection({ locale, targetType, targetId, slug, comments, user }: { locale: Locale; targetType: "post" | "product"; targetId: string; slug: string; comments: CommentItem[]; user: CurrentUser | null }) { const dictionary = getDictionary(locale); return <section className="mx-auto w-full max-w-3xl px-5 pb-16 sm:px-8 sm:pb-24" aria-labelledby="comments-title"><div className="border-t border-zinc-200 pt-10 dark:border-zinc-800"><h2 id="comments-title" className="text-2xl font-black">{dictionary.comments}</h2>{user ? <CommentForm targetType={targetType} targetId={targetId} slug={slug} locale={locale} /> : <p className="mt-5 rounded-2xl bg-zinc-50 p-5 text-sm text-zinc-600 dark:bg-zinc-900 dark:text-zinc-300">{dictionary.loginToComment} <Link href="/login" className="font-semibold text-emerald-700 dark:text-emerald-400">{locale === "fa" ? "ورود" : "Sign in"}</Link></p>}
    <div className="mt-8 space-y-4">{comments.length ? comments.map((comment) => <article key={comment.id} className="rounded-2xl border border-zinc-200 p-5 dark:border-zinc-800"><div className="flex flex-wrap items-center justify-between gap-3"><div><strong className="text-sm">{locale === "fa" ? comment.authorNameFa : comment.authorNameEn}</strong><time className="ms-3 text-xs text-zinc-500">{new Intl.DateTimeFormat(localeConfig[locale].dateLocale, { dateStyle: "medium" }).format(comment.createdAt)}</time></div>{comment.status !== "approved" ? <span className="rounded-full bg-amber-100 px-2.5 py-1 text-xs text-amber-800 dark:bg-amber-950 dark:text-amber-300">{locale === "fa" ? "در انتظار تأیید" : "Pending review"}</span> : null}</div><p className="mt-4 whitespace-pre-wrap leading-7 text-zinc-700 dark:text-zinc-300">{comment.body}</p>{user?.id === comment.authorId ? <div className="mt-4"><DeleteOwnCommentButton commentId={comment.id} targetType={targetType} slug={slug} locale={locale} /></div> : null}</article>) : <p className="text-sm text-zinc-500">{dictionary.noComments}</p>}</div></div></section>; }
