import { AdminCommentActions } from "@/components/comments/admin-comment-actions";
import { PanelListControls, PanelPagination } from "@/components/panel/list-controls";
import { PanelEmptyState, PanelPage, PanelPageHeader, PanelSurface, PanelTable, PanelTableCell } from "@/components/panel/ui";
import { getAdminComments, type CommentStatusFilter, type CommentTargetFilter } from "@/lib/comments/queries";
import { getPanelDictionary } from "@/lib/i18n/panel";
import { getPanelLocale } from "@/lib/i18n/panel-server";
import { getSearchParam, parseAdminListQuery, type AdminListSearchParams } from "@/lib/panel/pagination";

export default async function AdminCommentsPage({ searchParams }: { searchParams: Promise<AdminListSearchParams> }) { const [locale, query] = await Promise.all([getPanelLocale(), searchParams]); const listQuery = parseAdminListQuery(query); const statusValue = getSearchParam(query, "status"); const targetValue = getSearchParam(query, "target"); const status: CommentStatusFilter = statusValue === "pending" || statusValue === "approved" || statusValue === "rejected" ? statusValue : "all"; const target: CommentTargetFilter = targetValue === "blog" || targetValue === "shop" ? targetValue : "all"; const result = await getAdminComments({ ...listQuery, status, target }); const dictionary = getPanelDictionary(locale); const statusLabels = { pending: locale === "fa" ? "در انتظار" : "Pending", approved: locale === "fa" ? "تأییدشده" : "Approved", rejected: locale === "fa" ? "ردشده" : "Rejected" }; const statusStyles = { pending: "bg-amber-100 text-amber-800 dark:bg-amber-950 dark:text-amber-300", approved: "bg-emerald-100 text-emerald-800 dark:bg-emerald-950 dark:text-emerald-300", rejected: "bg-red-100 text-red-700 dark:bg-red-950 dark:text-red-300" };
  return <PanelPage><PanelPageHeader eyebrow={locale === "fa" ? "تعامل کاربران" : "Community"} title={locale === "fa" ? "مدیریت دیدگاه‌ها" : "Comment moderation"} description={locale === "fa" ? "دیدگاه‌های وبلاگ و فروشگاه را بررسی، تأیید، رد یا حذف کنید." : "Review, approve, reject, or delete blog and shop comments."} /><PanelSurface><PanelListControls action="/panel/admin/comments" locale={locale} query={listQuery.q} searchPlaceholder={locale === "fa" ? "جست‌وجوی متن، نویسنده یا محتوا…" : "Search text, author, or content…"} filters={[{ name: "status", label: dictionary.common.status, value: status, options: [{ value: "all", label: locale === "fa" ? "همه وضعیت‌ها" : "All statuses" }, { value: "pending", label: statusLabels.pending }, { value: "approved", label: statusLabels.approved }, { value: "rejected", label: statusLabels.rejected }] }, { name: "target", label: locale === "fa" ? "بخش" : "Section", value: target, options: [{ value: "all", label: locale === "fa" ? "همه بخش‌ها" : "All sections" }, { value: "blog", label: locale === "fa" ? "وبلاگ" : "Blog" }, { value: "shop", label: locale === "fa" ? "فروشگاه" : "Shop" }] }]} />{result.items.length ? <PanelTable minWidth="min-w-5xl" columns={[{ label: locale === "fa" ? "دیدگاه" : "Comment", className: "w-[36%]" }, { label: locale === "fa" ? "نویسنده" : "Author", className: "w-[17%]" }, { label: locale === "fa" ? "محتوا" : "Content", className: "w-[20%]" }, { label: dictionary.common.status, className: "w-[12%]" }, { label: dictionary.common.actions, className: "w-[15%]" }]}>{result.items.map((comment) => <tr key={comment.id}><PanelTableCell><p className="line-clamp-3 whitespace-pre-wrap leading-6">{comment.body}</p></PanelTableCell><PanelTableCell>{locale === "fa" ? comment.authorNameFa : comment.authorNameEn}</PanelTableCell><PanelTableCell><span className="line-clamp-2 text-zinc-600 dark:text-zinc-400">{locale === "en" ? comment.targetTitleEn || comment.targetTitleFa : comment.targetTitleFa}</span><span className="mt-1 block text-xs text-zinc-500">{comment.postId ? (locale === "fa" ? "وبلاگ" : "Blog") : (locale === "fa" ? "فروشگاه" : "Shop")}</span></PanelTableCell><PanelTableCell><span className={`rounded-full px-2.5 py-1 text-xs ${statusStyles[comment.status]}`}>{statusLabels[comment.status]}</span></PanelTableCell><PanelTableCell><AdminCommentActions commentId={comment.id} locale={locale} /></PanelTableCell></tr>)}</PanelTable> : <PanelEmptyState title={locale === "fa" ? "دیدگاهی پیدا نشد" : "No comments found"} description={locale === "fa" ? "دیدگاه‌های جدید کاربران در این بخش نمایش داده می‌شوند." : "New user comments will appear here for moderation."} />}<PanelPagination action="/panel/admin/comments" locale={locale} pagination={result} query={{ ...(listQuery.q ? { q: listQuery.q } : {}), ...(status !== "all" ? { status } : {}), ...(target !== "all" ? { target } : {}) }} /></PanelSurface></PanelPage>;
}
