name: Deploy Cactus to Dev Environment

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to Dev VPS via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 9011
          script: |
            cd /var/www/cactus-dev
            git fetch --all
            git reset --hard origin/develop

            # install dependencies & build on dev VPS
            npm install
            npm run build
            pm2 restart cactus-dev || pm2 start npm --name "cactus-dev" -- run start -- -p 3001

      - name: Create GitHub deployment status
        uses: chrnorm/deployment-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: development
          description: 'Deployed to Dev VPS'
          ref: develop
          state: success
