name: Deploy Cactus to Dev Environment

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to Dev VPS via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 9011
          script: |
            cd /var/www/cactus-dev
            git fetch --all
            git reset --hard origin/develop

            npm install
            npm run build

            # stop if running
            pm2 stop cactus-dev || true
            pm2 delete cactus-dev || true

            # start on port 3001
            PORT=3001 pm2 start npm --name "cactus-dev" -- run start

            # save PM2 process list
            pm2 save
